import '../../domain/entities/user_entity.dart';
import '../../domain/entities/chat_message_entity.dart';
import '../../domain/entities/chat_session_entity.dart';
import '../../domain/entities/pine_script_entity.dart';
import '../models/user_model.dart';

class MockDataSource {
  static final MockDataSource instance = MockDataSource._();
  MockDataSource._();

  UserEntity? _currentUser;

  UserEntity? get currentUser => _currentUser;

  Future<UserEntity> login(String email, String password) async {
    await Future.delayed(const Duration(seconds: 1));
    _currentUser = UserModel.mockUser;
    return _currentUser!;
  }

  Future<UserEntity> signUp(String email, String password, String name) async {
    await Future.delayed(const Duration(seconds: 1));
    _currentUser = UserModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: name,
      email: email,
      createdAt: DateTime.now(),
    );
    return _currentUser!;
  }

  Future<void> resetPassword(String email) async {
    await Future.delayed(const Duration(seconds: 1));
  }

  Future<void> verifyOTP(String email, String otp) async {
    await Future.delayed(const Duration(seconds: 1));
  }

  Future<void> signOut() async {
    _currentUser = null;
  }

  List<ChatSessionEntity> getMockSessions() {
    return [
      ChatSessionEntity(
        id: '1',
        title: 'Golden Cross Strategy',
        messages: _mockMessages,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
      ),
    ];
  }

  List<ChatMessageEntity> getMockMessages(String sessionId) {
    return List.from(_mockMessages);
  }

  Future<List<ChatSessionEntity>> getChatSessions() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return [
      ChatSessionEntity(
        id: '1',
        title: 'Golden Cross Strategy',
        messages: _mockMessages,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
      ),
    ];
  }

  Future<ChatMessageEntity> sendMessage(String content, {String? imagePath}) async {
    await Future.delayed(const Duration(seconds: 2));
    return ChatMessageEntity(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      content: 'I\'ve analyzed your request. Here is a Pine Script implementation based on your prompt.',
      role: MessageRole.assistant,
      timestamp: DateTime.now(),
      codeBlock: _generateMockCode(content),
    );
  }

  Future<List<PineScriptEntity>> getScripts() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return [
      PineScriptEntity(
        id: '1',
        filename: 'momentum_scalper.pine',
        version: 'v6',
        content: _mockPineScript,
        mode: 'Indicator',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
    ];
  }

  static const String _mockPineScript = '//@version=6\nindicator("Momentum Scalper AI", overlay=true, precision=2)\n\n// INPUTS\nrsiLength = input.int(14, "RSI Length")\nsmaLength = input.int(50, "SMA Length")\natrLength = input.int(14, "ATR Length")\natrMult = input.float(1.5, "ATR Multiplier")\n\n// CALCULATIONS\nrsi = ta.rsi(close, rsiLength)\nsma = ta.sma(close, smaLength)\natr = ta.atr(atrLength)\n\n// SIGNALS\nbuySignal = ta.crossover(rsi, 30) and close > sma\nsellSignal = ta.crossunder(rsi, 70) and close < sma\n\n// TP/SL\nlongSL = close - atr * atrMult\nlongTP = close + atr * atrMult * 2\n\n// PLOTS\nplotshape(buySignal, "Buy", shape.labelup, location.belowbar, color.new(#26A69A, 0), size=size.small)\nplotshape(sellSignal, "Sell", shape.labeldown, location.abovebar, color.new(#F7525F, 0), size=size.small)\n\nplot(sma, "SMA", color=color.gray, linewidth=1)\n';

  String _generateMockCode(String prompt) {
    return '//@version=6\nindicator("AI Generated: $prompt", overlay=true)\n\n// Generated by TrapAI Assistant\nrsi = ta.rsi(close, 14)\nplot(rsi, "RSI", color=color.blue)\n';
  }

  List<ChatMessageEntity> get _mockMessages => [
        ChatMessageEntity(
          id: '1',
          content: 'Can you convert this Pine Script indicator concept into v5 code?',
          role: MessageRole.user,
          timestamp: DateTime(2024),
        ),
        ChatMessageEntity(
          id: '2',
          content: 'Understood. I\'ve analyzed your chart image. Here is a Highs and Lows with non-repainting labels.',
          role: MessageRole.assistant,
          timestamp: DateTime.now(),
          codeBlock: _mockPineScript,
        ),
      ];
}
